---
title: "Data Assembly with mrgda"
author: "Michael McDermott & Eric Anderson"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{data-assembly}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, echo=FALSE, message=FALSE}
library(dplyr)

```

# Spec

```{r}
nm_spec <- yspec::ys_load(system.file("derived", "pk.yml", package = "mrgda"))

```

# Source Data

```{r}
src_path <- system.file("example-sdtm", package = "mrgda")

list.files(src_path)

src_list <- mrgda::read_src_dir(.path = src_path, .file_types = "xpt")

```

# Data Assembly (read in a pre-derived)

```{r}

nm_final <- readr::read_csv(system.file("derived", "pk.csv", package = "mrgda"), na = ".")

```



# Validate Data

```{r}

mrgda::nm_validate(.data = nm_final, .spec = nm_spec)

```

# Write Data

```{r}

# csv location, typically e.g. "data/derived/pk.csv"
derived_data_file <- file.path(tempdir(), "pk.csv")

derived_data_file

mrgda::nm_write(.data = nm_final, .spec = nm_spec, .file = derived_data_file)

```


# Session Info
```{r}
sessionInfo()
```
