empty_rows <- tibble::tibble(name = character(), value = character())

test_that("build_run_summary_lines includes header and all sections when both diffs exist", {
  standard_diffs <- tibble::tibble(
    name = "Rows",
    value = "1 added"
  )
  variable_diffs <- tibble::tibble(
    name = "WT",
    value = "3 diffs"
  )
  spec_diffs <- tibble::tibble(
    name = "Updated: WT",
    value = "short"
  )

  lines <- build_run_summary_lines(
    .data_standard_rows = standard_diffs,
    .data_variable_rows = variable_diffs,
    .spec_diff_rows = spec_diffs,
    .generated_at = as.POSIXct("2026-01-02 03:04:05", tz = "UTC"),
    .generated_by = "tester"
  )

  expect_equal(lines[1], "Generated at: 2026-01-02 03:04:05 +0000")
  expect_equal(lines[2], "Generated by: tester")
  expect_true(any(grepl("^Data changes:$", lines)))
  expect_true(any(grepl("^Variable changes:$", lines)))
  expect_true(any(grepl("^Spec changes:$", lines)))
  expect_true(any(grepl("Rows", lines, fixed = TRUE)))
  expect_true(any(grepl("WT", lines, fixed = TRUE)))
  expect_true(any(grepl("Updated: WT", lines, fixed = TRUE)))
})

test_that("build_run_summary_lines omits Variable diffs section when no variable diffs", {
  standard_diffs <- tibble::tibble(
    name = "Subjects",
    value = "No change"
  )

  lines <- build_run_summary_lines(
    .data_standard_rows = standard_diffs,
    .data_variable_rows = empty_rows,
    .spec_diff_rows = empty_rows,
    .generated_at = as.POSIXct("2026-01-02 03:04:05", tz = "UTC"),
    .generated_by = "tester"
  )

  expect_true(any(grepl("^Data changes:$", lines)))
  expect_false(any(grepl("^Variable changes:$", lines)))
  expect_true(any(grepl("^Spec changes:$", lines)))
  expect_true(any(grepl("^No spec diffs detected\\.$", lines)))
})

test_that("build_run_summary_lines includes no-diff text when both inputs are empty", {
  lines <- build_run_summary_lines(
    .data_standard_rows = empty_rows,
    .data_variable_rows = empty_rows,
    .spec_diff_rows = empty_rows,
    .generated_at = as.POSIXct("2026-01-02 03:04:05", tz = "UTC"),
    .generated_by = "tester"
  )

  expect_equal(lines[1], "Generated at: 2026-01-02 03:04:05 +0000")
  expect_equal(lines[2], "Generated by: tester")
  expect_true(any(grepl("^Data changes:$", lines)))
  expect_true(any(grepl("^No data diffs detected\\.$", lines)))
  expect_true(any(grepl("^Spec changes:$", lines)))
  expect_true(any(grepl("^No spec diffs detected\\.$", lines)))
})

test_that("build_run_summary_lines includes 'Compared against:' when .baseline_info is provided", {
  lines <- build_run_summary_lines(
    .data_standard_rows = empty_rows,
    .data_variable_rows = empty_rows,
    .spec_diff_rows = empty_rows,
    .generated_at = as.POSIXct("2026-01-02 03:04:05", tz = "UTC"),
    .generated_by = "tester",
    .baseline_info = "SVN r120 by jsmith (2026-01-15 10:30:45 -0500)"
  )

  expect_equal(lines[1], "Generated at: 2026-01-02 03:04:05 +0000")
  expect_equal(lines[2], "Generated by: tester")
  expect_equal(lines[3], "Compared against: SVN r120 by jsmith (2026-01-15 10:30:45 -0500)")
})

test_that("build_run_summary_lines omits 'Compared against:' when .baseline_info is NULL", {
  lines <- build_run_summary_lines(
    .data_standard_rows = empty_rows,
    .data_variable_rows = empty_rows,
    .spec_diff_rows = empty_rows,
    .generated_at = as.POSIXct("2026-01-02 03:04:05", tz = "UTC"),
    .generated_by = "tester"
  )

  expect_false(any(grepl("Compared against:", lines)))
})
