test_that("build_run_summary_lines includes header and both sections when both diffs exist", {
  data_diffs <- tibble::tibble(
    name = "N Rows Diff",
    value = "1 row(s) added"
  )
  spec_diffs <- tibble::tibble(
    name = "Spec Updated: WT",
    value = "short"
  )

  lines <- build_run_summary_lines(
    .data_diff_rows = data_diffs,
    .spec_diff_rows = spec_diffs,
    .generated_at = as.POSIXct("2026-01-02 03:04:05", tz = "UTC"),
    .generated_by = "tester"
  )

  expect_equal(lines[1], "Generated at: 2026-01-02 03:04:05 +0000")
  expect_equal(lines[2], "Generated by: tester")
  expect_true(any(grepl("^Data changes:$", lines)))
  expect_true(any(grepl("^Spec changes:$", lines)))
  expect_true(any(grepl("N Rows Diff", lines, fixed = TRUE)))
  expect_true(any(grepl("Spec Updated: WT", lines, fixed = TRUE)))
})

test_that("build_run_summary_lines includes no-diff text for missing sections", {
  data_diffs <- tibble::tibble(
    name = "N IDs Diff",
    value = "No change in N IDs"
  )

  lines <- build_run_summary_lines(
    .data_diff_rows = data_diffs,
    .spec_diff_rows = tibble::tibble(name = character(), value = character()),
    .generated_at = as.POSIXct("2026-01-02 03:04:05", tz = "UTC"),
    .generated_by = "tester"
  )

  expect_true(any(grepl("^Data changes:$", lines)))
  expect_true(any(grepl("^Spec changes:$", lines)))
  expect_true(any(grepl("^No spec diffs detected\\.$", lines)))
})

test_that("build_run_summary_lines includes no-diff text when both inputs are empty", {
  lines <- build_run_summary_lines(
    .data_diff_rows = tibble::tibble(name = character(), value = character()),
    .spec_diff_rows = tibble::tibble(name = character(), value = character()),
    .generated_at = as.POSIXct("2026-01-02 03:04:05", tz = "UTC"),
    .generated_by = "tester"
  )

  expect_equal(lines[1], "Generated at: 2026-01-02 03:04:05 +0000")
  expect_equal(lines[2], "Generated by: tester")
  expect_true(any(grepl("^Data changes:$", lines)))
  expect_true(any(grepl("^No data diffs detected\\.$", lines)))
  expect_true(any(grepl("^Spec changes:$", lines)))
  expect_true(any(grepl("^No spec diffs detected\\.$", lines)))
})
