#' Format a name-value tibble as indented, aligned lines
#'
#' @param .df A two-column tibble with `name` and `value` columns.
#' @return A character vector of formatted lines.
#' @noRd
format_kv_lines <- function(.df) {
  max_width <- max(nchar(.df$name))
  paste0("  ", format(.df$name, width = max_width), "   ", .df$value)
}

#' Print a name-value tibble to console with cli styling
#'
#' Values of `"No change"` are dimmed; all other values are highlighted.
#'
#' @param .df A two-column tibble with `name` and `value` columns.
#' @noRd
print_styled_kv <- function(.df) {
  max_width <- max(nchar(.df$name))
  for (i in seq_len(nrow(.df))) {
    padded_name <- format(.df$name[i], width = max_width)
    val <- .df$value[i]
    if (val == "No change") {
      styled_val <- cli::style_dim(val)
    } else {
      styled_val <- cli::style_bold(cli::col_cyan(val))
    }
    cat(paste0("  ", padded_name, "   ", styled_val, "\n"))
  }
}

#' Build summary lines for write_derived output
#'
#' @param .data_standard_rows A two-column tibble (`name`, `value`) of standard
#'   data diffs (Rows, Columns, Subjects).
#' @param .data_variable_rows A two-column tibble (`name`, `value`) of
#'   variable-specific data diffs (value changes, added/removed columns).
#' @param .spec_diff_rows A two-column tibble (`name`, `value`) of spec diffs.
#' @param .generated_at POSIXct time used in the summary header.
#' @param .generated_by Username used in the summary header.
#' @param .baseline_info Optional character string describing the baseline
#'   (e.g. `"SVN r120 by jsmith (2026-01-15 10:30:45 -0500)"`).
#'   When non-NULL a `"Compared against:"` line is added to the header.
#'
#' @return A character vector of lines for console/file output.
#' @noRd
build_run_summary_lines <- function(
    .data_standard_rows,
    .data_variable_rows,
    .spec_diff_rows,
    .generated_at = Sys.time(),
    .generated_by = Sys.info()[["user"]],
    .baseline_info = NULL
) {
  summary_lines <- c(
    paste0("Generated at: ", format(.generated_at, "%Y-%m-%d %H:%M:%S %z")),
    paste0("Generated by: ", .generated_by)
  )

  if (!is.null(.baseline_info)) {
    summary_lines <- c(summary_lines, paste0("Compared against: ", .baseline_info))
  }

  has_data_diffs <- nrow(.data_standard_rows) > 0 || nrow(.data_variable_rows) > 0

  if (has_data_diffs) {
    summary_lines <- c(summary_lines, "", "Data changes:", format_kv_lines(.data_standard_rows))

    if (nrow(.data_variable_rows) > 0) {
      summary_lines <- c(summary_lines, "", "Variable changes:", format_kv_lines(.data_variable_rows))
    }
  } else {
    summary_lines <- c(summary_lines, "", "Data changes:", "No data diffs detected.")
  }

  if (nrow(.spec_diff_rows) > 0) {
    summary_lines <- c(summary_lines, "", "Spec changes:", format_kv_lines(.spec_diff_rows))
  } else {
    summary_lines <- c(summary_lines, "", "Spec changes:", "No spec diffs detected.")
  }

  summary_lines
}
