#' Build summary lines for write_derived output
#'
#' @param .data_diff_rows A two-column tibble (`name`, `value`) of data diffs.
#' @param .spec_diff_rows A two-column tibble (`name`, `value`) of spec diffs.
#' @param .generated_at POSIXct time used in the summary header.
#' @param .generated_by Username used in the summary header.
#'
#' @return A character vector of lines for console/file output.
#' @noRd
build_run_summary_lines <- function(
    .data_diff_rows,
    .spec_diff_rows,
    .generated_at = Sys.time(),
    .generated_by = Sys.info()[["user"]]
) {
  summary_lines <- c(
    paste0("Generated at: ", format(.generated_at, "%Y-%m-%d %H:%M:%S %z")),
    paste0("Generated by: ", .generated_by)
  )

  if (nrow(.data_diff_rows) > 0) {
    data_diff_table <- knitr::kable(
      x = .data_diff_rows,
      format = "simple"
    )
    summary_lines <- c(summary_lines, "", "Data changes:", data_diff_table)
  } else {
    summary_lines <- c(summary_lines, "", "Data changes:", "No data diffs detected.")
  }

  if (nrow(.spec_diff_rows) > 0) {
    spec_diff_table <- knitr::kable(
      x = .spec_diff_rows,
      format = "simple"
    )
    summary_lines <- c(summary_lines, "", "Spec changes:", spec_diff_table)
  } else {
    summary_lines <- c(summary_lines, "", "Spec changes:", "No spec diffs detected.")
  }

  summary_lines
}
